configuration: Release
image: Visual Studio 2019
  
version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - gh-pages
  - 2.x

services:
- mssql2016
- mysql
- postgresql

nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
- cmd: build.cmd Pack

test_script:
  - dotnet test src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj -c Release

artifacts:
- path: artifacts/*.*nupkg
  name: NuGet
- path: artifacts/*.zip
  name: Zip

deploy:
- provider: NuGet
  server: hhttps://www.myget.org/F/quartznet/api/v3/
  symbol_server: hhttps://www.myget.org/F/quartznet/api/v3/
  api_key:
    secure: vXa9bqFD68eDW9epKh/lUK/h1OdIL92RiKAbc+JfVarllY962DWqMNSKOdvCopy/
  on:
    branch: master
