configuration: Release
image: Visual Studio 2019
  
version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true
branches:
  except:
  - gh-pages
  - 2.x

services:
- mysql
- postgresql

init:
  - net start MSSQL$SQL2019
 
nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
- cmd: build.cmd Pack

test_script:
  - dotnet test src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj -c Release

artifacts:
- path: artifacts/*.*nupkg
  name: NuGet
- path: artifacts/*.zip
  name: Zip

deploy:
- provider: NuGet
  server: https://www.myget.org/F/quartznet/api/v2/package
  api_key:
    secure: vXa9bqFD68eDW9epKh/lUK/h1OdIL92RiKAbc+JfVarllY962DWqMNSKOdvCopy/
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: ZNvfUugU3rYb9t+UWbqt/hspUNLQfjWCvxTFQDpxkEEjLuLNk6amLDfGZZuiZxn4
  on:
    branch: master
    appveyor_repo_tag: true    
